Repository PerfectWeek/web-api, pull requests merged in 2018-09, with the labels that each got.

#24 Update packages
  package-lock.json
  package.json
Labels: api

#30 Refactor/27 typeorm
  knexfile.js
  migrations/20180603182250_create-users-table.js
  migrations/20180604203152_add-users-updated_at.js
  migrations/20180609231352_add-users-email-index.js
  ormconfig.json
  package-lock.json
  package.json
  scripts/database_connect.sh
  sources/api/controllers/UserController.ts
  sources/api/middleware/loggedOnly.ts
  sources/api/models/UserModel.ts
  sources/api/views/UserView.ts
  sources/main.ts
  sources/model/entity/User.ts
  sources/model/migrations/1536018028568-CreateUserTable.ts
  sources/model/migrations/1536018155781-AddUpdatedAtTriger.ts
  sources/utils/DbConnection.ts
  sources/utils/apiException.ts
  sources/utils/checkEnvVariable.ts
  sources/utils/db.ts
  tsconfig.json
Labels: api, database, refactoring

#32 Feature/28 edit user
  sources/api/controllers/UserController.ts
  sources/api/routes/users/index.ts
Labels: Priority: Medium

#33 Delete user
  sources/api/controllers/UserController.ts
  sources/api/routes/users/index.ts
Labels: Priority: Medium, Type: Enhancement

#35 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#36 Change email validation regex
  sources/model/entity/User.ts
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#37 Add user verification
  sources/api/controllers/UserController.ts
Labels: Priority: Medium

#38 Change messages and code in authentication
  sources/api/middleware/loggedOnly.ts
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#41 Change response code in authentication
  sources/api/middleware/loggedOnly.ts
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement
