Repository PerfectWeek/web-api, pull requests merged in 2018-12, with the labels that each got.

#93 Auto generate swagger json
  openapi.yaml
  package.json
  resources/.gitignore
  resources/openapi.json
  scripts/swagger_generator.sh
  sources/api/routes/index.ts
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#92 Change group member deletion route
  openapi.yaml
  package-lock.json
  resources/openapi.json
  scripts/swagger_generator.sh
  sources/api/controllers/GroupController.ts
  sources/api/routes/groups/index.ts
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#97 Feature/96 calendar event entities
  sources/model/entity/Calendar.ts
  sources/model/entity/CalendarsToOwners.ts
  sources/model/entity/Event.ts
  sources/model/entity/EventsToAttendees.ts
  sources/model/migrations/1543884172010-CreateCalendarsAndEvents.ts
Labels: Priority: High, Status: Review Needed

#100 Feature/98 dummy routes
  openapi.yaml
  sources/api/controllers/CalendarController.ts
  sources/api/controllers/EventController.ts
  sources/api/controllers/GroupController.ts
  sources/api/controllers/UserController.ts
  sources/api/routes/calendars/index.ts
  sources/api/routes/events/index.ts
  sources/api/routes/groups/index.ts
  sources/api/routes/users/index.ts
Labels: Priority: High

#102 Fix http verb problem with group member removal
  sources/api/routes/groups/index.ts
Labels: Priority: High, Status: Review Needed, Type: Bug

#103 Feature/101 calendar routes
  __tests__/routes.postman_collection.json
  __tests__/routes.postman_environment.json
  sources/api/controllers/CalendarController.ts
  sources/api/routes/calendars/index.ts
  sources/api/routes/events/index.ts
  sources/api/views/CalendarView.ts
  sources/model/entity/Calendar.ts
  sources/model/entity/Event.ts
  sources/model/entity/User.ts
Labels: Priority: High

#105 Feature/104 user calendars
  __tests__/routes.postman_collection.json
  openapi.yaml
  sources/api/controllers/UserController.ts
  sources/api/views/CalendarsToOwnersView.ts
  sources/model/entity/User.ts
Labels: Priority: High, Status: Review Needed

#110 Feature/109 create default calendar
  __tests__/routes.postman_collection.json
  __tests__/routes.postman_environment.json
  sources/api/controllers/UserController.ts
  sources/model/entity/User.ts
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#112 Feature/111 create event from calendar
  __tests__/routes.postman_collection.json
  openapi.yaml
  sources/api/controllers/CalendarController.ts
  sources/api/routes/calendars/index.ts
  sources/api/views/EventView.ts
  sources/model/entity/CalendarsToOwners.ts
  sources/model/entity/Event.ts
Labels: Priority: High

#114 Feature/113 get calendar events
  __tests__/routes.postman_collection.json
  sources/api/controllers/CalendarController.ts
  sources/api/views/CalendarView.ts
  sources/api/views/EventView.ts
Labels: Priority: High

#117 Add Heroku Configuration
  Procfile
  __tests__/routes.auth.test.js
  ormconfig.js
  package-lock.json
  package.json
  resources/.gitignore
  resources/openapi/openapi.json
  scripts/heroku_migrate.sh
  scripts/heroku_start.sh
  scripts/test_database_connect.sh
  sources/api/routes/index.ts
  sources/main.ts
  sources/utils/DbConnection.ts
  sources/utils/loadRouters.ts
  tsconfig.json
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#106 Refacto/group model
  __tests__/routes.postman_collection.json
  openapi.yaml
  package-lock.json
  package.json
  resources/openapi/openapi.json
  sources/api/controllers/CalendarController.ts
  sources/api/controllers/GroupController.ts
  sources/api/controllers/UserController.ts
  sources/api/routes/groups/index.ts
  sources/api/views/GroupView.ts
  sources/api/views/GroupsToUsersView.ts
  sources/api/views/UserView.ts
  sources/model/entity/Calendar.ts
  sources/model/entity/CalendarsToOwners.ts
  sources/model/entity/Group.ts
  sources/model/entity/GroupsToUsers.ts
  sources/model/entity/PendingUser.ts
  sources/model/entity/User.ts
  sources/model/migrations/1543265697940-GroupsNbMembers.ts
  sources/model/migrations/1544073723525-GroupsRefacto.ts
  sources/utils/DbConnection.ts
Labels: Priority: High, Status: In Progress, Type: Enhancement

#122 [Hotfix] Change type for 'users' argument in add-members documentation
  openapi.yaml
  resources/openapi/openapi.json
Labels: Priority: Low, Status: Review Needed, Type: Bug, Type: Documentation

#127 Add default description in event
  sources/api/controllers/CalendarController.ts
Labels: [Priority] Low, [Status] Review Needed, [Type] Fix

#130 Resolves #118 "GET /groups/{group_id}/calendar return 404"
  openapi.yaml
  resources/openapi/openapi.json
Labels: [Priority] Low, [Status] Review Needed, [Type] Documentation, [Type] Fix

#129 Resolves #119 "POST /calendars/{calendar-id}/events: Body not mentioned in the documentation"
  openapi.yaml
  resources/openapi/openapi.json
Labels: [Priority] Low, [Status] Review Needed, [Type] Documentation, [Type] Fix

#133 [Hotfix] Fix array check in GroupController.addUsersToGroup
  sources/api/controllers/GroupController.ts
Labels: [Priority] High, [Status] Review Needed, [Type] Hotfix
