Repository PerfectWeek/web-api, pull requests merged in 2018-10, with the labels that each got.

#42 Quick start
  README.md
  scripts/database_connect.sh
  scripts/database_create.sh
Labels: Priority: Medium, Status: Review Needed

#40 Resolves #31 "Refactor Tests"
  .travis.yml
  __tests__/routes.auth.test.js
  __tests__/routes.postman_collection.json
  __tests__/routes.postman_environment.json
  package-lock.json
  package.json
  scripts/database_delete.sh
  scripts/database_migration.sh
  scripts/database_run.sh
  sources/api/controllers/UserController.ts
  sources/api/middleware/loggedOnly.ts
  sources/main.ts
  test/test.js
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#43 Add TravisCI shield in README.md
  README.md
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#45 Update bcrypt dependency
  package-lock.json
  package.json
Labels: Priority: Medium, Type: Bug

#47 Resolves #46 "[Tests] Change Docker Container Name"
  __tests__/routes.auth.test.js
  package.json
  scripts/database_delete.sh
  scripts/test_database_delete.sh
  scripts/test_database_run.sh
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#54 Resolves #53 "[Tests] Change Docker Test Container Port"
  __tests__/routes.auth.test.js
  ormconfig.js
  scripts/test_database_run.sh
Labels: Priority: Low, Status: Review Needed, Type: Enhancement

#57 Feature : Group basic management
  __tests__/routes.auth.test.js
  __tests__/routes.postman_collection.json
  __tests__/routes.postman_environment.json
  sources/api/controllers/GroupController.ts
  sources/api/controllers/UserController.ts
  sources/api/routes/groups/index.ts
  sources/api/views/GroupView.ts
  sources/api/views/UserView.ts
  sources/main.ts
  sources/model/entity/Group.ts
  sources/model/entity/User.ts
  sources/model/migrations/1539045820831-CreateGroups.ts
  sources/utils/removeDuplicates.ts
  sources/utils/removeIfExists.ts
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#59 [hotfix] Fix migration file for pending user
  package-lock.json
  sources/model/migrations/1539665284268-pending_users.ts
  sources/model/migrations/1539666286295-PendingUser.ts
Labels: Priority: Critical, Type: Bug
