Repository PerfectWeek/web-api, pull requests merged in 2018-11, with the labels that each got.

#66 Fix/62 users groups db relation
  sources/api/controllers/GroupController.ts
  sources/api/controllers/UserController.ts
  sources/model/entity/Group.ts
  sources/model/entity/GroupsToUsers.ts
  sources/model/entity/User.ts
  sources/model/migrations/1541780060535-GroupUserRelationRemove.ts
  sources/model/migrations/1541972481578-GroupsToUsers.ts
Labels: Priority: High, Status: Review Needed

#69 Update Readme
  README.md
Labels: Priority: Low

#71 Dummy group routes
  __tests__/routes.postman_collection.json
  __tests__/routes.postman_environment.json
  sources/api/controllers/GroupController.ts
  sources/api/controllers/UserController.ts
  sources/api/routes/groups/index.ts
  sources/api/views/GroupView.ts
Labels: Priority: High, Status: Review Needed, Type: Enhancement

#72 Refacto/group model
  sources/api/controllers/GroupController.ts
  sources/model/entity/Group.ts
  sources/utils/removeDuplicates.ts
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement, Type: Maintenance

#74 [Swagger] Add openapi.json route
  resources/openapi.json
  sources/api/routes/index.ts
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#75 Write api documentation
  openapi.yaml
  resources/openapi.json
  sources/api/routes/groups/index.ts
  sources/api/routes/index.ts
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement, Type: Maintenance

#76 Update documentation route in README.md
  README.md
Labels: Priority: Low, Status: Review Needed, Type: Maintenance

#85 [Groups] Fix dummy response content on PUT /groups/members/pseudo
  sources/api/controllers/GroupController.ts
Labels: Priority: High, Status: Review Needed, Type: Bug

#79 Add members count in Group resource
  openapi.yaml
  resources/openapi.json
  sources/api/views/GroupView.ts
  sources/model/entity/Group.ts
  sources/model/migrations/1543265697940-GroupsNbMembers.ts
Labels: Priority: Medium, Status: Review Needed, Type: Enhancement

#82 [Groups] Allow creation of Group with only owner inside
  __tests__/routes.postman_collection.json
  sources/api/controllers/GroupController.ts
Labels: Priority: Medium, Status: Review Needed, Type: Maintenance
