Repository PerfectWeek/web-api, pull requests merged in 2018-06, with the labels that each got.

#2 Make the "updated_at" field be updated automatically
  migrations/20180604203152_add-users-updated_at.js
Labels: enhancement, review

#4 Add authentication functions
  package.json
  sources/api/controllers/users.ts
  sources/api/models/User.ts
  sources/api/routes/auth/login/index.ts
  sources/utils/encrypt.ts
  tsconfig.json
Labels: review

#10 Feature/9 env
  sources/api/controllers/users.ts
  sources/api/models/User.ts
  sources/main.ts
  sources/utils/checkEnvVariable.ts
  sources/utils/db.ts
  tsconfig.json
Labels: review

#14 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: review

#12 Feature/5 user view
  sources/api/controllers/UserController.ts
  sources/api/models/UserModel.ts
  sources/api/routes/auth/login/index.ts
  sources/api/routes/users/index.ts
  sources/api/views/UserView.ts
  tsconfig.json
Labels: api, review

#15 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: review

#13 Drop duplicate index on users table
  migrations/20180603182250_create-users-table.js
  migrations/20180604203152_add-users-updated_at.js
  migrations/20180609231352_add-users-email-index.js
Labels: database, review

#8 Add ApiException
  sources/api/controllers/UserController.ts
  sources/api/models/UserModel.ts
  sources/main.ts
  sources/utils/apiException.ts
  sources/utils/checkEnvVariable.ts
  tsconfig.json
Labels: enhancement, review

#19 Add loggedOnly method
  sources/api/controllers/UserController.ts
  sources/api/middlewares/loggedOnly.ts
  sources/api/models/UserModel.ts
  sources/api/routes/users/index.ts
  tsconfig.json
Labels: api, review

#20 Add Windows compatibility
  scripts/Unix/connect_local_db.sh
  scripts/Unix/create_local_db.sh
  scripts/Windows/connect_local_db.cmd
  scripts/create_local_db.sh
  sources/utils/loadRouters.ts
Labels: bug, review
