Repository PerfectWeek/web-api, pull requests merged in 2019-01, with the labels that each got.

#148 Feature/70 google calendar sync
  .gitignore
  package-lock.json
  package.json
  sources/api/controllers/CalendarController.ts
  sources/api/controllers/EventController.ts
  sources/api/controllers/GoogleCalendarController.ts
  sources/api/routes/externals/index.ts
  sources/model/entity/Event.ts
  sources/model/entity/GoogleCalendarCredentials.ts
  sources/model/migrations/1547478763922-googleCalendarCredentials.ts
  sources/utils/GoogleCalendarUtils.ts
Labels: [Priority] High, [Status] Review Needed, [Type] Feature

#152 Change redirect route email validation
  README.md
  sources/api/controllers/UserController.ts
Labels: [Priority] Medium, [Status] Review Needed, [Type] Feature

#153 Setup Editorconfig and Commit hook
  .editorconfig
  __tests__/routes.postman_environment.json
  openapi.yaml
  package-lock.json
  package.json
  sources/api/controllers/GoogleCalendarController.ts
  sources/model/entity/Event.ts
  sources/model/entity/EventsToAttendees.ts
  sources/utils/accountVerification.ts
  sources/utils/emailSender.ts
Labels: [Priority] Low, [Status] Review Needed, [Type] Feature
